Add flexom server definition
iMicknl/python-overkiz-api pull request #378
Opened 2022-02-19 21:52 UTC by phimage

Hi,
Just adding another server endpoint
Flexom v3 is another rebranding of overkiz cloud, here for Bouygue

I could list my devices using my login/password and code from README

2022-02-19 21:57 UTC, tetienne requested changes
Some typo.

Thx for your contributions. I didn't know this solution. https://www.overkiz.com/flexom-3-0-le-logement-connecte-par-bouygues-immobilier-et-overkiz/

Have you been able to call the `get_setup` method?

2022-02-19 21:57 UTC, tetienne commented on README.md
> +- Bouygue Flexom
```suggestion
- Bouygues Flexom
```

2022-02-19 21:57 UTC, tetienne commented on pyoverkiz/const.py
> +        manufacturer="Bouygue",
```suggestion
        manufacturer="Bouygues",
```

2022-02-20 05:52 UTC, phimage commented
I will fix the typo

I launch `get_setup` and it failed to decode my gateway
Value 47 for HATTARA RAIL DIN https://www.overkiz.com/wp-content/uploads/2018/10/FICHE_PRODUIT_DIN_RAIL_2019_FR-.pdf
I will add it in the PR
 
I see that some location info are empty like country
(in another library that use this info to load some translation file it make it crash 😣)

2022-02-20 13:01 UTC, iMicknl approved these changes
Good find! Do you plan to use the HA integration?

2022-02-20 13:03 UTC, iMicknl commented
@phimage could you run the `get_diagnostic_data()` function perhaps? It would be good to add a setup.json definition for your device as well, for our automated tests.

2022-02-20 13:08 UTC, merged

2022-02-21 08:40 UTC, phimage commented
> Good find! Do you plan to use the HA integration?

I will make a try, but not now, it’s a new appartement and I do not live in it yet

I have just tested HomeBrige for HomeKit, it’s laggy

> @phimage could you run the `get_diagnostic_data()` function perhaps? It would be good to add a setup.json definition for your device as well, for our automated tests.

I will

2022-04-06 21:22 UTC, mbrd1 commented
You mention Flexom V3 but there is also Flexom V2 which uses the same hardware but uses the Ubiant Cloud.
Do you think something is possible for this one too?

![3222D6CB-5D3A-48D8-B66A-BABDE73C3340](https://user-images.githubusercontent.com/103149301/162073336-60c0eb34-4b07-40a5-be79-a0af86c85bdf.jpeg)

2022-04-06 21:26 UTC, iMicknl commented
@mbrd1 how do you connect to Flexom V2? If you can link me the Android app, I can have a look if it would be supported.

2022-04-06 21:34 UTC, mbrd1 commented
@iMicknl 

With an mail/password but it uses the Ubiant server : hemisphere.ubiant.com

I have contacted Overkiz to see if it is possible not to go through Ubiant, I am waiting for their answer.

Flexom V2 : 
https://play.google.com/store/apps/details?id=com.ubiant.flexom&hl=fr&gl=US

2022-04-07 05:43 UTC, phimage commented
Hi,
for me v2 is different
https://github.com/rsauget/flexom-lib
with different url
https://github.com/rsauget/flexom-lib/blob/b92f332e319367651df6c10fd45a0e932da5f71f/src/ubiant/ubiant.ts#L19
hemis , like v2 app
https://play.google.com/store/apps/details?id=com.ubiant.flexom&hl=fr&gl=US

but maybe they make a bridge




Le mer. 6 avr. 2022 à 23:34, mbrd1 ***@***.***> a écrit :

> @iMicknl <https://github.com/iMicknl>
>
> With an mail/password but it uses the Ubiant server :
> hemisphere.ubiant.com
>
> I have contacted Overkiz to see if it is possible not to go through
> Ubiant, I am waiting for their answer.
>
> Flexom V2 :
> https://play.google.com/store/apps/details?id=com.ubiant.flexom&hl=fr&gl=US
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/iMicknl/python-overkiz-api/pull/378#issuecomment-1090830743>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACDW56C7SRKD4J4RA5PDWMTVDX7NXANCNFSM5O3P5G2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>