Add MeasuredValueType enum
iMicknl/python-overkiz-api pull request #640
Opened 2022-10-18 07:56 UTC by tetienne

2022-10-18 08:40 UTC, tetienne commented on pyoverkiz/enums/measured_value_type.py
> +class MeasuredValueType(str, Enum):
Well OverkizAttribute contains the name of the attribute, `MeasuredValueType` here and not the available values.  If I follow you, we should do the same for DataType and  ProductType right?

2022-10-18 10:03 UTC, iMicknl commented on pyoverkiz/enums/measured_value_type.py
> +class MeasuredValueType(str, Enum):
You are right, I was a bit confused by everything being prefixed with core:. But this enum is the value indeed, not the key.

2022-10-18 10:04 UTC, iMicknl commented on pyoverkiz/enums/measured_value_type.py
> +    ELECTRICAL_ENERGY_IN_K_WH = "core:ElectricalEnergyInKWh"
```suggestion
    ELECTRICAL_ENERGY_IN_KWH = "core:ElectricalEnergyInKWh"
```

2022-10-18 12:07 UTC, iMicknl commented on pyoverkiz/enums/measured_value_type.py
> +    ENERGY_INK_CAL = "core:EnergyInkCal"
```suggestion
    ENERGY_IN_KCAL = "core:EnergyInkCal"
```

Would this be kilocalorie?

2022-10-18 12:43 UTC, tetienne commented on pyoverkiz/enums/measured_value_type.py
> +    ENERGY_INK_CAL = "core:EnergyInkCal"
I would say yes.

2022-10-18 19:31 UTC, iMicknl approved these changes

2022-10-18 19:32 UTC, iMicknl requested changes
Please add the file to https://github.com/iMicknl/python-overkiz-api/blob/main/pyoverkiz/enums/__init__.py as well, so we can import from .enums

2022-10-19 06:39 UTC, tetienne commented
@iMicknl done

2022-10-19 07:18 UTC, iMicknl approved these changes

2022-10-19 07:18 UTC, merged