Fix detection of error messages.
iMicknl/python-overkiz-api pull request #843
Opened 2023-05-03 16:40 UTC by shypike

Don't try to do exact matches, but use "in".
One issue being that the message usually looks like:
  '"No registered event listener."'
(Note the extra quotes.)

2023-05-03 16:43 UTC, shypike commented
This will make recovery of the "No registered event listener" error during local access of a Somfy box actually work.
The recovery code is correct, but the "==" matching spoils it here.

2023-05-03 21:14 UTC, iMicknl commented
Thanks @shypike, we will have a look! Interesting that they throw a slight different error locally... 

How are you using the local integration? Via your own Python code or via HA?

2023-05-05 20:28 UTC, iMicknl commented
@shypike we actually have a version of Overkiz with a local integration ready, for months, but it is not polished. If you are want to contribute, you are more than welcome. https://github.com/home-assistant/core/pull/71644

See https://community.home-assistant.io/t/overkiz-integration-local-api-development-testers-topic/485264

2023-05-06 19:06 UTC, iMicknl commented
@vlebourl, @egguy do we want to merge all these changes in, or just the one that is required for this usecase?

2023-05-07 07:14 UTC, shypike commented
@iMicknl I'll have a look, but with summer coming :)

2023-05-19 12:22 UTC, tetienne approved these changes

2023-05-19 12:24 UTC, iMicknl requested changes
@shypike we would prefer to only have the messages changes where there is no exact match, for clarity. Or even add exact string matches in the if statement, instead of an `in message`.

Would you be able to make this change, so we can merge it in?

2023-05-20 08:49 UTC, shypike commented
@iMicknl What is not clear to me is whether the "No registered event listener" is unique for local access. If it's valid for both local and remote, using exact string matches will not work. Unless your original code was already incorrect for remote.
Personally I'm no fan of exact strings matches because it makes it more likely to fail due to trivial changes.
I would go for an "in" for the "No registered event listener" message and no change to other strings.
BTW: my local hack (using the above changes) is rock solid has been running successfully for three weeks now. Unlike the remote version which is always hampered by the sub-par Somfy servers.

2023-05-20 08:58 UTC, iMicknl commented
I will try to simulate the error on cloud API to see if this is incorrect in the client library, or if this is something that is using another error message in the local API.

The reason we would like exact matches is too be as strict as possible, if Overkiz/Somfy would change the error messages, we probably would need changes anyway, thus it is good to have it fail. We rather have everything as strict as possible.

Great to hear that your local hack is working great! We still need to full implement this in HA. Can you perhaps verify if you have the same issue? https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/102

2023-05-20 19:34 UTC, shypike commented
@iMicknl I have mostly RTS devices and only two IO screens. The RTS devices don't give any feedback, so always have state unknown. I'll keep an eye on IO. However, I've tried to set debug mode on but nothing is logged.
```
logger:
  default: error
  logs:
    pyoverkiz: debug
    homeassistant.components.overkiz: debug
```
The above lines in the config should do the trick. What am I doing wrong?

2023-05-20 19:47 UTC, shypike commented
My last commit just strips off outer single quotes. That should care of the difference between local and remote messages.

2023-05-20 19:47 UTC, iMicknl approved these changes

2023-05-20 20:59 UTC, merged

2023-05-21 11:41 UTC, shypike commented
Pfff, I stripped the wrong kind of quotes. When I read my first text again, I see that "local" adds double quotes and not single quotes.
So the best solution would be:
```
.strip("\"'")
```

2023-05-28 21:31 UTC, iMicknl commented
@shypike can you save some JSON files of the error? So we can add testcases for this.